// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2oxuplpjDgRRjc7--vdANNySMcyyWdg',
    appId: '1:440378994073:web:ad82b60f9db4cb4bf8f708',
    messagingSenderId: '440378994073',
    projectId: 'mawdoo3taskk',
    authDomain: 'mawdoo3taskk.firebaseapp.com',
    storageBucket: 'mawdoo3taskk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5D76D47YpT0QD3n9_3F3hnKjQ7sgP0g',
    appId: '1:440378994073:android:8badf48b93615157f8f708',
    messagingSenderId: '440378994073',
    projectId: 'mawdoo3taskk',
    storageBucket: 'mawdoo3taskk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNnP3fo75B7Ksh6cfdwyM_SSOelgxmvOc',
    appId: '1:440378994073:ios:0a6ddcf6f06df441f8f708',
    messagingSenderId: '440378994073',
    projectId: 'mawdoo3taskk',
    storageBucket: 'mawdoo3taskk.appspot.com',
    iosBundleId: 'com.example.wodoo33',
  );
}
